package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 22-may-2018 21:23:13 by Hibernate Tools 4.3.1



/**
 * Aplicacionpuesto generated by hbm2java
 */
public class Aplicacionpuesto  implements java.io.Serializable {


     private Integer pkIdAplicacion;
     private Integer oferente;
     private Integer puesto;

    public Aplicacionpuesto() {
    }

    public Aplicacionpuesto(Integer oferente, Integer puesto) {
       this.oferente = oferente;
       this.puesto = puesto;
    }
   
    public Integer getPkIdAplicacion() {
        return this.pkIdAplicacion;
    }
    
    public void setPkIdAplicacion(Integer pkIdAplicacion) {
        this.pkIdAplicacion = pkIdAplicacion;
    }
    public Integer getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Integer oferente) {
        this.oferente = oferente;
    }
    public Integer getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Integer puesto) {
        this.puesto = puesto;
    }




}


