package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 22-may-2018 21:23:13 by Hibernate Tools 4.3.1



/**
 * Caracteristicasoferente generated by hbm2java
 */
public class Caracteristicasoferente  implements java.io.Serializable {


     private Integer pkIdCaracteristicas;
     private Integer oferente;
     private Integer subcategoria;

    public Caracteristicasoferente() {
    }

    public Caracteristicasoferente(Integer oferente, Integer subcategoria) {
       this.oferente = oferente;
       this.subcategoria = subcategoria;
    }
   
    public Integer getPkIdCaracteristicas() {
        return this.pkIdCaracteristicas;
    }
    
    public void setPkIdCaracteristicas(Integer pkIdCaracteristicas) {
        this.pkIdCaracteristicas = pkIdCaracteristicas;
    }
    public Integer getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Integer oferente) {
        this.oferente = oferente;
    }
    public Integer getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Integer subcategoria) {
        this.subcategoria = subcategoria;
    }




}


