package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 16:26:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer pkIdCategoria;
     private String nombreCat;
     private Integer ultimoUsuario;
     private Date fechaCambios;
     

    public Categoria() {
    }

	
    public Categoria(String nombreCat) {
        this.nombreCat = nombreCat;
    }
    public Categoria(String nombreCat, Integer ultimoUsuario, Date fechaCambios) {
       this.nombreCat = nombreCat;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
      
    }
   
    public Integer getPkIdCategoria() {
        return this.pkIdCategoria;
    }
    
    public void setPkIdCategoria(Integer pkIdCategoria) {
        this.pkIdCategoria = pkIdCategoria;
    }
    public String getNombreCat() {
        return this.nombreCat;
    }
    
    public void setNombreCat(String nombreCat) {
        this.nombreCat = nombreCat;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }





}


