package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 21/04/2018 11:42:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int pkIdEmp;
     private Localizacion localizacion;
     private Usuario usuario;
     private String nombre;
     private String correo;
     private String telefono;
     private String descripcion;
     private int ultimoUsuario;
     private Date fechaCambios;
     private Set<Puesto> puestos = new HashSet<Puesto>(0);

    public Empresa() {
    }

	
    public Empresa(int pkIdEmp, Localizacion localizacion, Usuario usuario, String nombre, String correo, String telefono, int ultimoUsuario, Date fechaCambios) {
        this.pkIdEmp = pkIdEmp;
        this.localizacion = localizacion;
        this.usuario = usuario;
        this.nombre = nombre;
        this.correo = correo;
        this.telefono = telefono;
        this.ultimoUsuario = ultimoUsuario;
        this.fechaCambios = fechaCambios;
    }
    public Empresa(int pkIdEmp, Localizacion localizacion, Usuario usuario, String nombre, String correo, String telefono, String descripcion, int ultimoUsuario, Date fechaCambios, Set<Puesto> puestos) {
       this.pkIdEmp = pkIdEmp;
       this.localizacion = localizacion;
       this.usuario = usuario;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.descripcion = descripcion;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
       this.puestos = puestos;
    }
   
    public int getPkIdEmp() {
        return this.pkIdEmp;
    }
    
    public void setPkIdEmp(int pkIdEmp) {
        this.pkIdEmp = pkIdEmp;
    }
    public Localizacion getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(Localizacion localizacion) {
        this.localizacion = localizacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(int ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public Set<Puesto> getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set<Puesto> puestos) {
        this.puestos = puestos;
    }




}


