package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 8:54:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.List;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer pkIdEmp;
     private Localizacion localizacion;
     private Usuario usuario;
     private String nombre;
     private String correo;
     private String telefono;
     private String descripcion;
     private Integer ultimoUsuario;
     private Date fechaCambios;
     private List<Puesto> puestos;

    public Empresa() {
    }

	
    public Empresa(Localizacion localizacion, String nombre, String correo, String telefono) {
        this.localizacion = localizacion;
        this.nombre = nombre;
        this.correo = correo;
        this.telefono = telefono;
    }
    public Empresa(Localizacion localizacion, Usuario usuario, String nombre, String correo, String telefono, String descripcion, Integer ultimoUsuario, Date fechaCambios, List<Puesto> puestos) {
       this.localizacion = localizacion;
       this.usuario = usuario;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.descripcion = descripcion;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
       this.puestos = puestos;
    }
   
    public Integer getPkIdEmp() {
        return this.pkIdEmp;
    }
    
    public void setPkIdEmp(Integer pkIdEmp) {
        this.pkIdEmp = pkIdEmp;
    }
    public Localizacion getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(Localizacion localizacion) {
        this.localizacion = localizacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public List<Puesto> getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(List<Puesto> puestos) {
        this.puestos = puestos;
    }




}


