package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 04-may-2018 22:36:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Localizacion generated by hbm2java
 */
public class Localizacion  implements java.io.Serializable {


     private Integer pkIdLocalizacion;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Oferente> oferentes = new HashSet<Oferente>(0);

    public Localizacion() {
    }

	
    public Localizacion(BigDecimal latitud, BigDecimal longitud) {
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Localizacion(BigDecimal latitud, BigDecimal longitud, Set<Empresa> empresas, Set<Oferente> oferentes) {
       this.latitud = latitud;
       this.longitud = longitud;
       this.empresas = empresas;
       this.oferentes = oferentes;
    }
   
    public Integer getPkIdLocalizacion() {
        return this.pkIdLocalizacion;
    }
    
    public void setPkIdLocalizacion(Integer pkIdLocalizacion) {
        this.pkIdLocalizacion = pkIdLocalizacion;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set<Oferente> oferentes) {
        this.oferentes = oferentes;
    }




}


