package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 8:54:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.List;

/**
 * Localizacion generated by hbm2java
 */
public class Localizacion  implements java.io.Serializable {


     private Integer pkIdLocalizacion;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private List<Empresa> empresas;
     private List<Oferente> oferentes;

    public Localizacion() {
    }

	
    public Localizacion(BigDecimal latitud, BigDecimal longitud) {
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Localizacion(BigDecimal latitud, BigDecimal longitud, List<Empresa> empresas, List<Oferente> oferentes) {
       this.latitud = latitud;
       this.longitud = longitud;
       this.empresas = empresas;
       this.oferentes = oferentes;
    }
   
    public Integer getPkIdLocalizacion() {
        return this.pkIdLocalizacion;
    }
    
    public void setPkIdLocalizacion(Integer pkIdLocalizacion) {
        this.pkIdLocalizacion = pkIdLocalizacion;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public List<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(List<Empresa> empresas) {
        this.empresas = empresas;
    }
    public List<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(List<Oferente> oferentes) {
        this.oferentes = oferentes;
    }




}


