package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 17-abr-2018 15:58:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oferente generated by hbm2java
 */
public class Oferente  implements java.io.Serializable {


     private String pkCedula;
     private Localizacion localizacion;
     private Usuario usuario;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String nacionalidad;
     private String correo;
     private String residencia;
     private Set<Subcategoria> subcategorias = new HashSet<Subcategoria>(0);
     private Set<Puesto> puestos = new HashSet<Puesto>(0);

    public Oferente() {
    }

	
    public Oferente(String pkCedula, Usuario usuario, String nombre, String apellido1, String apellido2, String nacionalidad, String correo) {
        this.pkCedula = pkCedula;
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.nacionalidad = nacionalidad;
        this.correo = correo;
    }
    public Oferente(String pkCedula, Localizacion localizacion, Usuario usuario, String nombre, String apellido1, String apellido2, String nacionalidad, String correo, String residencia, Set<Subcategoria> subcategorias, Set<Puesto> puestos) {
       this.pkCedula = pkCedula;
       this.localizacion = localizacion;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.nacionalidad = nacionalidad;
       this.correo = correo;
       this.residencia = residencia;
       this.subcategorias = subcategorias;
       this.puestos = puestos;
    }
   
    public String getPkCedula() {
        return this.pkCedula;
    }
    
    public void setPkCedula(String pkCedula) {
        this.pkCedula = pkCedula;
    }
    public Localizacion getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(Localizacion localizacion) {
        this.localizacion = localizacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public Set<Subcategoria> getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set<Subcategoria> subcategorias) {
        this.subcategorias = subcategorias;
    }
    public Set<Puesto> getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set<Puesto> puestos) {
        this.puestos = puestos;
    }




}


