package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 17-abr-2018 15:58:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int pkIdPuesto;
     private Empresa empresa;
     private String tipoPublicacion;
     private String salario;
     private Set<Oferente> oferentes = new HashSet<Oferente>(0);
     private Set<Subcategoria> subcategorias = new HashSet<Subcategoria>(0);

    public Puesto() {
    }

	
    public Puesto(int pkIdPuesto, Empresa empresa, String tipoPublicacion, String salario) {
        this.pkIdPuesto = pkIdPuesto;
        this.empresa = empresa;
        this.tipoPublicacion = tipoPublicacion;
        this.salario = salario;
    }
    public Puesto(int pkIdPuesto, Empresa empresa, String tipoPublicacion, String salario, Set<Oferente> oferentes, Set<Subcategoria> subcategorias) {
       this.pkIdPuesto = pkIdPuesto;
       this.empresa = empresa;
       this.tipoPublicacion = tipoPublicacion;
       this.salario = salario;
       this.oferentes = oferentes;
       this.subcategorias = subcategorias;
    }
   
    public int getPkIdPuesto() {
        return this.pkIdPuesto;
    }
    
    public void setPkIdPuesto(int pkIdPuesto) {
        this.pkIdPuesto = pkIdPuesto;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getTipoPublicacion() {
        return this.tipoPublicacion;
    }
    
    public void setTipoPublicacion(String tipoPublicacion) {
        this.tipoPublicacion = tipoPublicacion;
    }
    public String getSalario() {
        return this.salario;
    }
    
    public void setSalario(String salario) {
        this.salario = salario;
    }
    public Set<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set<Oferente> oferentes) {
        this.oferentes = oferentes;
    }
    public Set<Subcategoria> getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set<Subcategoria> subcategorias) {
        this.subcategorias = subcategorias;
    }




}


