package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 8:54:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer pkIdPuesto;
     private Empresa empresa;
     private String tipoPublicacion;
     private BigDecimal salario;
     private Integer ultimoUsuario;
     private Date fechaCambios;
     private String nombre;
     private Set<Oferente> oferentes = new HashSet<Oferente>(0);
     private Set<Subcategoria> subcategorias = new HashSet<Subcategoria>(0);

    public Puesto() {
    }

	
    public Puesto(Empresa empresa, String tipoPublicacion, BigDecimal salario, String nombre) {
        this.empresa = empresa;
        this.tipoPublicacion = tipoPublicacion;
        this.salario = salario;
        this.nombre = nombre;
    }
    public Puesto(Empresa empresa, String tipoPublicacion, BigDecimal salario, Integer ultimoUsuario, Date fechaCambios, String nombre, Set<Oferente> oferentes, Set<Subcategoria> subcategorias) {
       this.empresa = empresa;
       this.tipoPublicacion = tipoPublicacion;
       this.salario = salario;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
       this.nombre = nombre;
       this.oferentes = oferentes;
       this.subcategorias = subcategorias;
    }
   
    public Integer getPkIdPuesto() {
        return this.pkIdPuesto;
    }
    
    public void setPkIdPuesto(Integer pkIdPuesto) {
        this.pkIdPuesto = pkIdPuesto;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getTipoPublicacion() {
        return this.tipoPublicacion;
    }
    
    public void setTipoPublicacion(String tipoPublicacion) {
        this.tipoPublicacion = tipoPublicacion;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set<Oferente> oferentes) {
        this.oferentes = oferentes;
    }
    public Set<Subcategoria> getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set<Subcategoria> subcategorias) {
        this.subcategorias = subcategorias;
    }




}


