package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 8:54:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.List;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer pkIdSubcategoria;
     private Categoria categoria;
     private String nombreSub;
     private Integer ultimoUsuario;
     private Date fechaCambios;
     private List<Puesto> puestos ;
     private List<Oferente> oferentes ;

    public Subcategoria() {
    }

	
    public Subcategoria(Categoria categoria, String nombreSub) {
        this.categoria = categoria;
        this.nombreSub = nombreSub;
    }
    public Subcategoria(Categoria categoria, String nombreSub, Integer ultimoUsuario, Date fechaCambios, List<Puesto> puestos, List<Oferente> oferentes) {
       this.categoria = categoria;
       this.nombreSub = nombreSub;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
       this.puestos = puestos;
       this.oferentes = oferentes;
    }
   
    public Integer getPkIdSubcategoria() {
        return this.pkIdSubcategoria;
    }
    
    public void setPkIdSubcategoria(Integer pkIdSubcategoria) {
        this.pkIdSubcategoria = pkIdSubcategoria;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreSub() {
        return this.nombreSub;
    }
    
    public void setNombreSub(String nombreSub) {
        this.nombreSub = nombreSub;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public List<Puesto> getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(List<Puesto> puestos) {
        this.puestos = puestos;
    }
    public List<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(List<Oferente> oferentes) {
        this.oferentes = oferentes;
    }




}


