package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 16:26:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer pkIdSubcategoria;
     private Integer categoria;
     private String nombreSub;
     private Integer ultimoUsuario;
     private Date fechaCambios;
     

    public Subcategoria() {
    }

	
    public Subcategoria(Integer categoria, String nombreSub) {
        this.categoria = categoria;
        this.nombreSub = nombreSub;
    }
    public Subcategoria(Integer categoria, String nombreSub, Integer ultimoUsuario, Date fechaCambios) {
       this.categoria = categoria;
       this.nombreSub = nombreSub;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
      
    }
   
    public Integer getPkIdSubcategoria() {
        return this.pkIdSubcategoria;
    }
    
    public void setPkIdSubcategoria(Integer pkIdSubcategoria) {
        this.pkIdSubcategoria = pkIdSubcategoria;
    }
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }
    public String getNombreSub() {
        return this.nombreSub;
    }
    
    public void setNombreSub(String nombreSub) {
        this.nombreSub = nombreSub;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    



}


