package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 04-may-2018 22:36:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer pkIdSubcategoria;
     private Categoria categoria;
     private String nombreSub;
     private int ultimoUsuario;
     private Date fechaCambios;
     private Set<Puesto> puestos = new HashSet<Puesto>(0);
     private Set<Oferente> oferentes = new HashSet<Oferente>(0);

    public Subcategoria() {
    }

	
    public Subcategoria(Categoria categoria, String nombreSub, int ultimoUsuario, Date fechaCambios) {
        this.categoria = categoria;
        this.nombreSub = nombreSub;
        this.ultimoUsuario = ultimoUsuario;
        this.fechaCambios = fechaCambios;
    }
    public Subcategoria(Categoria categoria, String nombreSub, int ultimoUsuario, Date fechaCambios, Set<Puesto> puestos, Set<Oferente> oferentes) {
       this.categoria = categoria;
       this.nombreSub = nombreSub;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaCambios = fechaCambios;
       this.puestos = puestos;
       this.oferentes = oferentes;
    }
   
    public Integer getPkIdSubcategoria() {
        return this.pkIdSubcategoria;
    }
    
    public void setPkIdSubcategoria(Integer pkIdSubcategoria) {
        this.pkIdSubcategoria = pkIdSubcategoria;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreSub() {
        return this.nombreSub;
    }
    
    public void setNombreSub(String nombreSub) {
        this.nombreSub = nombreSub;
    }
    public int getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(int ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public Set<Puesto> getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set<Puesto> puestos) {
        this.puestos = puestos;
    }
    public Set<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set<Oferente> oferentes) {
        this.oferentes = oferentes;
    }




}


