package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 22-may-2018 21:23:13 by Hibernate Tools 4.3.1



/**
 * Subcategoriapuesto generated by hbm2java
 */
public class Subcategoriapuesto  implements java.io.Serializable {


     private Integer pkIdSubcategoriapuesto;
     private Integer puesto;
     private Integer subcategoria;

    public Subcategoriapuesto() {
    }

    public Subcategoriapuesto(Integer puesto, Integer subcategoria) {
       this.puesto = puesto;
       this.subcategoria = subcategoria;
    }
   
    public Integer getPkIdSubcategoriapuesto() {
        return this.pkIdSubcategoriapuesto;
    }
    
    public void setPkIdSubcategoriapuesto(Integer pkIdSubcategoriapuesto) {
        this.pkIdSubcategoriapuesto = pkIdSubcategoriapuesto;
    }
    public Integer getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Integer puesto) {
        this.puesto = puesto;
    }
    public Integer getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Integer subcategoria) {
        this.subcategoria = subcategoria;
    }




}


