package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 05-may-2018 16:26:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer pkUsuario;
     private String usuario;
     private String pkEmail;
     private String password;
     private Date fechaCreacion;
     private int tipo;
     private Date fechaCambios;
     private Integer ultimoUsuario;
    


    public Usuario() {
    }

	
    public Usuario(String usuario, String pkEmail, String password, Date fechaCreacion, int tipo) {
        this.usuario = usuario;
        this.pkEmail = pkEmail;
        this.password = password;
        this.fechaCreacion = fechaCreacion;
        this.tipo = tipo;
    }
    public Usuario(String usuario, String pkEmail, String password, Date fechaCreacion, int tipo, Date fechaCambios, Integer ultimoUsuario) {
       this.usuario = usuario;
       this.pkEmail = pkEmail;
       this.password = password;
       this.fechaCreacion = fechaCreacion;
       this.tipo = tipo;
       this.fechaCambios = fechaCambios;
       this.ultimoUsuario = ultimoUsuario;
      
    }
   
    public Integer getPkUsuario() {
        return this.pkUsuario;
    }
    
    public void setPkUsuario(Integer pkUsuario) {
        this.pkUsuario = pkUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPkEmail() {
        return this.pkEmail;
    }
    
    public void setPkEmail(String pkEmail) {
        this.pkEmail = pkEmail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Date getFechaCambios() {
        return this.fechaCambios;
    }
    
    public void setFechaCambios(Date fechaCambios) {
        this.fechaCambios = fechaCambios;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }


}


