package cr.ac.una.prograiv.proyecto.bolsaempleo.domain;
// Generated 21/04/2018 11:42:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int pkUsuario;
     private String usuario;
     private String pkEmail;
     private String password;
     private Date fechaCreacion;
     private String tipo;
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Oferente> oferentes = new HashSet<Oferente>(0);

    public Usuario() {
    }

	
    public Usuario(int pkUsuario, String usuario, String pkEmail, String password, Date fechaCreacion, String tipo) {
        this.pkUsuario = pkUsuario;
        this.usuario = usuario;
        this.pkEmail = pkEmail;
        this.password = password;
        this.fechaCreacion = fechaCreacion;
        this.tipo = tipo;
    }
    public Usuario(int pkUsuario, String usuario, String pkEmail, String password, Date fechaCreacion, String tipo, Set<Empresa> empresas, Set<Oferente> oferentes) {
       this.pkUsuario = pkUsuario;
       this.usuario = usuario;
       this.pkEmail = pkEmail;
       this.password = password;
       this.fechaCreacion = fechaCreacion;
       this.tipo = tipo;
       this.empresas = empresas;
       this.oferentes = oferentes;
    }
   
    public int getPkUsuario() {
        return this.pkUsuario;
    }
    
    public void setPkUsuario(int pkUsuario) {
        this.pkUsuario = pkUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPkEmail() {
        return this.pkEmail;
    }
    
    public void setPkEmail(String pkEmail) {
        this.pkEmail = pkEmail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Oferente> getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set<Oferente> oferentes) {
        this.oferentes = oferentes;
    }




}


